services:
  docs:
    build:
      context: docs/.
      dockerfile: Dockerfile

    ports:
      - '8000:8000' # Documentation

    volumes:
      - ./docs/src:/app/src

    env_file:
      - .env.local

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile

    environment:
      - ENV_FILE_PATH=.env.local

    volumes:
      - ./frontend/src:/app/frontend/src
      - ./.env.local:/app/frontend/.env.local:ro

      # Mount git info to container
      - ./.git/HEAD:/app/frontend/.git/HEAD
      - ./.git/refs/heads/:/app/frontend/.git/refs/heads/

    ports:
      - '3000:3000' # NextJS page
      - '6006:6006' # Storybook

    depends_on:
      - postgres

  graphql:
    build:
      context: .
      dockerfile: ./backend/graphQL/Dockerfile

    environment:
      - ENV_FILE_PATH=.env.local

    volumes:
      - ./.env.local:/app/backend/graphQL/.env.local:ro
      - ./backend/graphQL/src:/app/backend/graphQL/src

    ports:
      - '4000:4000' # Frontend as Webpage
      - '5555:5555' # Prisma Studio

    depends_on:
      - postgres

  postgres:
    image: postgres:latest

    ports:
      - '5432:5432'

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: myTopSecretPassword
      POSTGRES_DB: eMeal_menuplanung

    volumes:
      - postgress-data_new2:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - '9090:9090'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  # To eventually offload to Tempo...
  tempo:
    image: grafana/tempo:latest
    command: ['-config.file=/etc/tempo/tempo.yml']
    volumes:
      - ./observability/tempo/tempo.yml:/etc/tempo/tempo.yml
      - tempo-data:/tmp/tempo
    ports:
      - '3200' # tempo
      - '4317' # otlp grpc
      - '4318' # otlp http

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - '3100:3100'
    command:
      - --config.file=/mnt/config/loki-config.yml
    volumes:
      - ./observability/loki/loki-config.yml:/mnt/config/loki-config.yml:ro

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning

    environment:
      - GF_LOG_LEVEL=error
    ports:
      - '9000:3000' # localhost:9000 for accessing grafana

volumes:
  postgress-data_new2:
    driver: local
  prometheus-storage:
    driver: local
  grafana-storage:
    driver: local
  tempo-data:
    driver: local
