version: "3.7"

services:

  frontend:

    build:
      context: ./frontend
      dockerfile: Dockerfile

    environment:
      - ENV_FILE_PATH=/app/.env.local

    volumes:
      - ./frontend/src:/app/src
      - ./.env.local:/app/.env.local:ro

      # Mount git info to container
      - ./.git/HEAD:/app/.git/HEAD
      - ./.git/refs/heads/:/app/.git/refs/heads/

    ports:
      - "3000:3000"

    depends_on:
      - mongo-db

  graphql:

    build:
      context: ./backend/graphQL
      dockerfile: Dockerfile

    environment:
      - ENV_FILE_PATH=.env.local

    volumes:
      - ./.env.local:/app/.env.local:ro
      - ./backend/graphQL/src:/app/src

    ports:
      - "4000:4000"

    depends_on:
      - mongo-db

  mongo-db:

    build:
      context: backend/mongoDB
      dockerfile: Dockerfile

    ports:
      - "27017:27017"

    restart: always

    environment:
      - ENV_FILE_PATH=/etc/mongo/.env.local
    volumes:
      - ./.env.local:/etc/mongo/.env.local:ro
