version: '3.7'

services:
  docs:
    build:
      context: docs/.
      dockerfile: Dockerfile

    ports:
      - '8000:8000' # Documentation

    volumes:
      - ./docs/src:/app/src

    env_file:
      - .env.local

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile

    environment:
      - ENV_FILE_PATH=.env.local

    volumes:
      - ./frontend/src:/app/frontend/src
      - ./.env.local:/app/frontend/.env.local:ro

      # Mount git info to container
      - ./.git/HEAD:/app/frontend/.git/HEAD
      - ./.git/refs/heads/:/app/frontend/.git/refs/heads/

    ports:
      - '3000:3000' # NextJS page
      - '6006:6006' # Storybook

    depends_on:
      - mongo-db

  graphql:
    build:
      context: .
      dockerfile: ./backend/graphQL/Dockerfile

    environment:
      - ENV_FILE_PATH=.env.local

    volumes:
      - ./.env.local:/app/backend/graphQL/.env.local:ro
      - ./backend/graphQL/src:/app/backend/graphQL/src

    ports:
      - '4000:4000' # Frontend as Webpage
      - '5555:5555' # Prisma Studio

    depends_on:
      - mongo-db

  mongo-db:
    build:
      context: backend/mongoDB
      dockerfile: Dockerfile

    hostname: mongo-db

    ports:
      - '27017:27017'
      - '27018:27018'

    restart: always

    environment:
      - ENV_FILE_PATH=/etc/mongo/.env.local

    volumes:
      - ./.env.local:/etc/mongo/.env.local:ro
      - mongo-db-data:/data/db
      - mongo-db-config:/data/configdb

  prometheus:
    image: prom/prometheus
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - '9090:9090'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  # To eventually offload to Tempo...
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo/tempo.yml" ]
    volumes:
      - ./observability/tempo/tempo.yml:/etc/tempo/tempo.yml
      - tempo-data:/tmp/tempo
    ports:
      - "3200"   # tempo
      - "4317"  # otlp grpc
      - "4318"  # otlp http

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning

    environment:
      - GF_LOG_LEVEL=error
    ports:
      - '9000:3000' # localhost:9000 for accessing grafana

volumes:
  mongo-db-data:
    driver: local
  mongo-db-config:
    driver: local
  prometheus-storage:
    driver: local
  grafana-storage:
    driver: local
  tempo-data:
    driver: local
