version: "3.7"

services:

  frontend:

    build:
      context: ./frontend
      dockerfile: Dockerfile

    environment:
      - ENV_FILE_PATH=.env.local

    volumes:
      - ./frontend/src:/app/src
      - ./.env.local:/app/.env.local:ro

    ports:
      - "3000:3000"

    depends_on:
      - mongo-db

  mongo-db:

    image: mongo

    build:
      context: ./backend/database
      dockerfile: Dockerfile

    ports:
      - "27017:27017"
    restart: always

    environment:
      - ENV_FILE_PATH=/etc/mongo/.env.local
    volumes:
      - ./.env.local:/etc/mongo/.env.local:ro

  mongo-setup:
    image: mongo
    depends_on:
      - mongo-db
    volumes:
      - ./backend/database:/scripts:ro
    restart: "no"
    entrypoint: [ "bash", "/scripts/mongo_setup.sh" ]
