apiVersion: 1

datasources:
  - name: 'prometheus'
    access: proxy
    type: prometheus
    url: http://prometheus:9090
    isDefault: true

  - name: 'Tempo'
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus