apiVersion: 1

datasources:
  - name: 'prometheus'
    access: proxy
    type: prometheus
    url: http://prometheus:9090
    isDefault: true

  - name: 'Tempo'
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus

      tracesToLogs:
        datasourceUid: 'Loki'
        spanStartTimeShift: '-30m'
        spanEndTimeShift: '30m'
        filterByTraceID: true
        filterBySpanID: false
        tags: ['container']

  - name: 'Loki'
    type: loki
    url: http://loki:3100

    jsonData:
      maxLines: 1000
      derivedFields:
        # Field with internal link pointing to data source in Grafana.
        # Right now, Grafana supports only Jaeger and Zipkin data sources as link targets.
        - datasourceUid: 'Tempo' # not a uid, bug
          matcherRegex: 'trace_id\":\"(\w+)\"'
          name: 'trace_id'
          # url will be interpreted as query for the datasource
          url: '$${__value.raw}'
          urlDisplayLabel: 'Trace in Tempo'

        - matcherRegex: 'frontend_page_id\":\"(\w+)\"'
          name: 'frontend_page_id'
          url: 'explore?schemaVersion=1&panes=%7B%220cy%22:%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22nextjs-frontend%5C%22%7D%20%7C%3D%20%60$${__value.raw}%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-5d%22,%22to%22:%22now%22%7D%7D%7D&orgId=1'
          urlDisplayLabel: 'All Logs of this Request'

        - matcherRegex: 'current_path":"([\w/]+)"'
          name: 'current_path'
          url: 'explore?schemaVersion=1&panes=%7B%220cy%22:%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22nextjs-frontend%5C%22%7D%20%7C%3D%20%60$${__value.raw}%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-5d%22,%22to%22:%22now%22%7D%7D%7D&orgId=1'
          urlDisplayLabel: 'All Logs of this URL'
