scalar JSON
scalar Date

"""
A directive to limit the number of requests to a field or an object.

This is implemented using https://github.com/ravangen/graphql-rate-limit
"""
directive @rateLimit(
  """
  Number of occurrences allowed over duration.
  """
  limit: Int! = 60
  """
  Number of seconds before limit is reset.
  """
  duration: Int! = 60
) on OBJECT | FIELD_DEFINITION

interface Node {
  """
  A unique identifier for an object. This should be unique among all types.
  """
  id: ID!
}

interface Edge {
  cursor: String!
  node: Node!
}

interface Connection {
  """
  A list of edges.
  """
  edges: [Edge]

  """
  Information to aid in pagination.
  """
  pageInfo: PageInfo!

  """
  Identifies the total count of items in the connection.
  """
  totalCount: Int!
}

"""
The number of participants for a camp, meal, ..., e.g. 10 total, 3 vegetarians, 2 vegans, 1 leader.
"""
type ParticipantCount {
  total: Int!
  vegetarians: Int!
  vegans: Int!
  leaders: Int!
}

"""
Defines the search criteria for users.
"""
input UserSearchCriteria {
  partialUsername: String
}

type Query @rateLimit(limit: 100, duration: 60) {
  checkUsername(username: String): Acknowledgement

  """
  Returns a list of users according to the search criteria. The result is a list of users
  matching the search criteria, only users with isHiddenUser set to false are returned.

  If no search criteria are provided, all users are returned according to the pagination.
  If no pagination is provided, the first 10 users are returned.

  You the limit is capped at 100 users. This API endpoint has a rate limit of 20 requests per minute.
  """
  users(criteria: UserSearchCriteria, pagination: Pagination): UserConnection!
  user(id: ID!): User

  """
  Returns a list of all camps of the current user according to the pagination.
  """
  camps(
    """
    Returns the elements in the list that come after the specified cursor.
    """
    after: String

    """
    Returns the elements in the list that come before the specified cursor.
    """
    before: String

    """
    Returns the first _n_ elements from the list.
    """
    first: Int

    """
    Returns the last _n_ elements from the list.
    """
    last: Int

    """
    Ordering options for repositories returned from the connection
    """
    orderBy: CampOrder

    """
    The search criteria for the camps
    """
    filterBy: CampSearchCriteria
  ): CampConnection!

  camp(id: ID!): Camp

  # returns a list of meals according to the search criteria
  meals: MealConnection!
  meal(id: ID!): Meal
}

type Mutation @rateLimit(limit: 10, duration: 60) {
  updateUser(username: String, shareEmail: Boolean, newUser: Boolean): Acknowledgement
  createNewUser(name: String, email: String, password: String): Acknowledgement
  updateDay(camp_id: ID!, date: Date, description: String): Acknowledgement
  updateMeal(id: ID!, name: String, description: String): Acknowledgement

  createCamp(name: String!, description: String!): CampAcknowledgement
  updateCamp(id: ID!, name: String, description: String, year: Int): CampAcknowledgement
}

type Subscription {
  user: User
  camp(id: ID!): Camp
}

interface Acknowledgement {
  success: Boolean
  error: String

  node: Node
}

type CampAcknowledgement implements Acknowledgement {
  success: Boolean
  error: String

  node: Camp
}
