scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s

    static_configs:
      - targets: ['host.docker.internal:4000']
        labels:
          service: 'prisma-engine'
          group: 'development'

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
