{
 "title": "Prisma Engine",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Client Queries Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(prisma_client_queries_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95% Total Query Duriation",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(prisma_client_queries_duration_histogram_ms_bucket[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Datasource Operation Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(prisma_datasource_queries_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}