name: Continuous integration
'on':
  pull_request:
    branch:
      - master

jobs:
  version-check:
  - id: check # This will be the reference for getting the outputs.
    uses: EndBug/version-check@v1 # You can choose the version/branch you prefer.

    with: # All these parameters are optional, check their descriptions to see if you need them.
      file-url: https://raw.githubusercontent.com/wp99cp/menuplanung/master/package.json
      static-checking: localIsNew
