name: Continuous integration
'on':
  pull_request:
    branch:
      - master

jobs:
  version-check:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Checl Version Number
        id: check # This will be the reference for getting the outputs.
        uses: EndBug/version-check@v1
        with:
          file-url: https://raw.githubusercontent.com/wp99cp/menuplanung/master/package.json
          static-checking: localIsNew

      - name: Log when changed
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'
        output:
          version_changed:
            value: true

      - name: Log when unchanged
        if: steps.check.outputs.changed != 'true'
        run: 'echo "No version change :/"'
