name: Continuous integration
'on':
  pull_request:
    branch:
      - master

jobs:
  version-check:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Checl Version Number
        id: check # This will be the reference for getting the outputs.
        uses: EndBug/version-check@v1
        with:
          file-url: https://raw.githubusercontent.com/wp99cp/menuplanung/master/package.json
          static-checking: localIsNew

      - name: Log when unchanged
        if: steps.check.outputs.changed != 'true'
        run: exit 1

      - name: 'Comment PR'
        uses: actions/github-script@0.3.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            github.issues.createComment({ issue_number, owner, repo, body: 'Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})' });

      - run: exit 0
