name: Create Release

# See docu/Continuous Integration And_General_Tests.md for detailed information-module.
on:
  push:
    branches:
      - master

jobs:
  create_release_tag:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: '22'

      - name: Load Version of Latest Release
        id: check # This will be the reference for getting the outputs.
        uses: EndBug/version-check@v3
        with:
          file-name: ./frontend/package.json
          file-url: ::before
          static-checking: localIsNew

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ steps.check.outputs.version }}
          name: Version ${{ steps.check.outputs.version }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

  build_and_deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci && npm run build:prod
        working-directory: frontend
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: ./frontend
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CEVIZH11_MENUPLANUNG }}'
          channelId: live
          projectId: cevizh11-menuplanung
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

  execute_release_scripts:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v7

      #install the python needed
      - name: setup python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'

      - name: install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ./deployment_scripts/requirements.txt

      # run copy_help_messages_to_production_DB.py
      - name: execute py script
        env:
          MENUPLANUNG_PRIVATE_KEY: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CEVIZH11_MENUPLANUNG__PRIVATE_KEY }}'
          CEVIZH11_PRIVATE_KEY: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CEVIZH11__PRIVATE_KEY }}'
        run: python ./deployment_scripts/copy_help_messages_to_production_DB.py

